resource_registry:
  OS::TripleO::Tasks::ControllerDeployedServerPreConfig: OS::Heat::None
  OS::TripleO::Tasks::ControllerDeployedServerPostConfig: OS::Heat::None
  OS::TripleO::Tasks::ControllerDeployedServerPostPuppetRestart: /home/stack/output/extraconfig/tasks/post_puppet_pacemaker_restart.yaml
